version: "3"
services:
  server:
    build: ./server
    image: php:apache-mysqli
    container_name: "shopping-cart-server"
    ports:
      - 8080:80
    volumes:
      - ./server/html:/var/www/html:z
      - ./server/includes:/var/www/includes:z
      - ./server/apache-conf:/etc/apache2:z
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: shopping_cart
    depends_on:
      - db
  db:
    image: mariadb
    container_name: "shopping-cart-db"
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:z
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: shopping_cart
  client:
    build: ./client
    image: nginx:dev
    container_name: "shopping-cart-client"
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
    ports:
      - 80:80

volumes: 
  mariadb:
