version: "3"
services:
  server:
    build: ./server
    image: php:apache-mysqli
    container_name: "shopping-cart-server"
    ports:
      - 8080:80
    volumes:
      - ./server/html:/var/www/html:z
      - ./server/apache-conf:/etc/apache2:z
    depends_on:
      - db
  db:
    image: mariadb
    container_name: "shopping-cart-db"
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
  client:
    build: ./client
    image: nginx:dev
    container_name: "shopping-cart-client"
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
    ports:
      - 80:80

volumes: 
  mariadb:
